# Server
server:
  port: 8081
  
# default yaml file
spring:
  application:
    name: your_springboot_project_name
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your_database_name
    username:
    password:
    initialization-mode:
  jpa:
    hibernate:
      ddl-auto: create 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # mongo
  data:
    mongodb:
      uri: mongodb://localhost:27017/your_db_name
  #reactive_mysql
  r2dbc:
    url: r2dbc:mysql://localhost:3306/mydb
    username: your_mysql_username
    password: your_mysql_password
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30000
  # Oauth2 Client
  security:
    oauth2:
      client:
        registration:
          google: # Google OAuth2 클라이언트 설정 예시
            client-id: 
            client-secret: 
            scope: profile, email
            redirect-uri: 
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub


# Gmail SMTP
mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
